- name: Install certbot package
  when: ansible_os_family == 'Debian'
  apt:
    name: certbot
    state: present

- name: Install certbot package
  when: ansible_os_family == 'RedHat'
  yum:
    name: certbot
    state: present

- name: Create scripts folder
  file:
      path: /root/scripts
      state: directory
      mode: '0755'

- name: Copy certs renew script
  copy:
    src: scripts/certs_renew.sh
    dest: /root/scripts/certs_renew.sh
    owner: root
    group: root
    mode: '0755'
    backup: yes

- name: Make symlink of certs renew to cron daily
  file:
    src: '/root/scripts/certs_renew.sh'
    dest: '/etc/cron.daily/certs-renew'
    owner: root
    group: root
    state: link
    force: yes

- name: Register account (if not exist)
  shell: if [ `ls /etc/letsencrypt/accounts/acme-v01.api.letsencrypt.org/directory/ | wc -l` -eq 0 ]; then certbot register -n --agree-tos -m admin@localhost; fi

