- name: Install mysql packages
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - mariadb-server
    - mariadb-client

- name: Set default mysql config
  when: ansible_os_family == 'Debian'
  copy:
    src: config/mysql/mysqld_debian.cnf
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart mysql
  when: ansible_os_family == 'Debian'
  systemd:
    name: mysql
    state: restarted
