- name: Update packages list (Debian)
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Check packages and install missing (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apg
    - apt-transport-https
    - apt-utils
    - aptitude
    - bzip2
    - ca-certificates
    - ftp
    - git
    - htop
    - iotop
    - logrotate
    - man-db
    - mc
    - ncdu
    - p7zip
    - sshfs
    - sudo
    - sysstat
    - telnet
    - tmux
    - vim
    - wget
    - zip
    - unzip

