- name: Add php repository (Debian)
  when: ansible_os_family == 'Debian'
  apt_repository:
    repo: "ppa:ondrej/php"
    state: present

- name: Update packages list (Debian)
  when: ansible_os_family == 'Debian'
  apt: update_cache=yes

- name: Install php packages (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - php7.3-bcmath
        - php7.3-cli
        - php7.3-common
        - php7.3-fpm
        - php7.3-gd
        - php7.3-intl
        - php7.3-json
        - php7.3-mbstring
        - php7.3-mcrypt
        - php7.3-mysql
        - php7.3-opcache
        - php7.3-xml
        - php7.3-xsl
        - php7.3-zip

- name: Set default php-cli config (Debian)
  when: ansible_os_family == 'Debian'
  copy:
    src: config/php/cli/php.ini
    dest: /etc/php/7.1/cli/php.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set default php-fpm config (Debian)
  when: ansible_os_family == 'Debian'
  copy:
    src: config/php/fpm/php.ini
    dest: /etc/php/7.1/fpm/php.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart php-fpm (Debian)
  when: ansible_os_family == 'Debian'
  systemd:
    name: php7.3-fpm.service
    state: restarted
