- name: Add Remi php repository (RedHat)
  when: ansible_os_family == 'RedHat'
  yum: 
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Enable remi php 7.1 repository (RedHat)
  when: ansible_os_family == 'RedHat'
  command: yum-config-manager --enable remi-php73

- name: Install php packages (RedHat)
  when: ansible_os_family == 'RedHat'
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - php73-php-bcmath
        - php73-php-cli
        - php73-php-common
        - php73-php-fpm
        - php73-php-gd
        - php73-php-intl
        - php73-php-json
        - php73-php-mbstring
        - php73-php-mcrypt
        - php73-php-mysql
        - php73-php-opcache
        - php73-php-xml
        - php73-php-xsl
        - php73-php-zip

- name: Make symlink to php cli
  file:
    src: '/opt/remi/php73/root/usr/bin/php'
    dest: '/usr/bin/php'
    owner: root
    group: root
    state: link
    mode: '755'

- name: Set default php config (RedHat)
  when: ansible_os_family == 'RedHat'
  copy:
    src: config/php/fpm/php.ini
    dest: /etc/opt/remi/php73/php.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Create directory for fpm sockets (RedHat)
  when: ansible_os_family == 'RedHat'
  file:
    path: /run/php
    state: directory

- name: Restart php-fpm (RedHat)
  when: ansible_os_family == 'RedHat'
  systemd:
    name: php73-php-fpm.service
    state: restarted

- name: Enable php-fpm service (RedHat)
  service:
    name: php73-php-fpm
    enabled: yes

