#- name: Add php repository (Debian)
#  when: ansible_os_family == 'Debian'
#  apt_repository:
#    repo: "ppa:ondrej/php"
#    state: present

- name: Update packages list (Debian)
  when: ansible_os_family == 'Debian'
  apt: update_cache=yes

- name: Install php packages (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
        - php8.1-bcmath
        - php8.1-cli
        - php8.1-common
        - php8.1-curl
        - php8.1-fpm
        - php8.1-gd
        - php8.1-intl
        - php8.1-mbstring
        - php8.1-mysql
        - php8.1-opcache
        - php8.1-xml
        - php8.1-xsl
        - php8.1-zip

- name: Set default php-cli config (Debian)
  when: ansible_os_family == 'Debian'
  copy:
    src: config/php/cli/php.ini
    dest: /etc/php/8.1/cli/php.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Set default php-fpm config (Debian)
  when: ansible_os_family == 'Debian'
  copy:
    src: config/php/fpm/php.ini
    dest: /etc/php/8.1/fpm/php.ini
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Restart php-fpm (Debian)
  when: ansible_os_family == 'Debian'
  systemd:
    name: php8.1-fpm.service
    state: restarted
