- name: Copy logrotate config
  when: ansible_os_family == 'Debian'
  copy:
    src: config/logrotate/homes_debian
    dest: /etc/logrotate.d/homes
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Copy logrotate config
  when: ansible_os_family == 'RedHat'
  copy:
    src: config/logrotate/homes_redhat
    dest: /etc/logrotate.d/homes
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: Create scripts folder
  file:
      path: /root/scripts
      state: directory
      mode: '0755'

- name: Create config templates folder
  file:
      path: /root/scripts/conf_templates
      state: directory
      mode: '0755'

- name: Copy site creation scripts
  copy:
    src: scripts/add_site.sh
    dest: /root/scripts/add_site.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy site deletion scripts
  copy:
    src: scripts/del_site.sh
    dest: /root/scripts/del_site.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy wordpress installation script
  copy:
    src: scripts/install_wp.sh
    dest: /root/scripts/install_wp.sh
    owner: root
    group: root
    mode: '0755'

- name: Copy fpm conf template
  copy:
    src: scripts/conf_templates/fpm.conf
    dest: /root/scripts/conf_templates/fpm.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy nginx precert conf template
  copy:
    src: scripts/conf_templates/nginx_template_precert.conf
    dest: /root/scripts/conf_templates/nginx_template_precert.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy nginx final conf template
  copy:
    src: scripts/conf_templates/nginx_template_ssl.conf
    dest: /root/scripts/conf_templates/nginx_template_ssl.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy db backup script
  copy:
    src: scripts/backup/backup_db.sh
    dest: /root/scripts/backup/backup_db.sh
    owner: root
    group: root
    mode: '0755'

- name: Make in cron.daily symlink to db backup
  file:
      src: '/root/scripts/backup/backup_db.sh'
      dest: '/etc/cron.daily/backup-db'
      owner: root
      group: root
      state: link
      mode: '755'

- name: Copy files backup script
  copy:
    src: scripts/backup/backup_files.sh
    dest: /root/scripts/backup/backup_files.sh
    owner: root
    group: root
    mode: '0755'

- name: Make in cron.daily symlink to files backup
  file:
      src: '/root/scripts/backup/backup_files.sh'
      dest: '/etc/cron.daily/backup-files'
      owner: root
      group: root
      state: link
      mode: '755'

