- name: Install web server
  hosts: all
  become: yes
  become_user: root
  tasks:
    - import_tasks: tasks/packages_update_cache_debian.yml
    - import_tasks: tasks/nginx.yml

    - import_tasks: tasks/php_debian.yml
      when: ansible_os_family == 'Debian'
    - import_tasks: tasks/php_redhat.yml
      when: ansible_os_family == 'RedHat'

    - import_tasks: tasks/mysql_debian.yml
      when: ansible_os_family == 'Debian'
    - import_tasks: tasks/mysql_redhat.yml
      when: ansible_os_family == 'RedHat'

    - import_tasks: tasks/put_scripts.yml
    - import_tasks: tasks/certbot.yml

